# Two command lines I got sick of typing in.  :)
#   Written by Ryan C. Gordon.
#
# This Makefile falls under the GPL. See LICENSE.TXT.

all:
	jikes `find ./ -name "*.java" |xargs`

clean:
	rm `find ./ -name "*.class" |xargs`



