/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class last_toby_turtlespace_sdl_SDLRenderer */

#ifndef _Included_last_toby_turtlespace_sdl_SDLRenderer
#define _Included_last_toby_turtlespace_sdl_SDLRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     last_toby_turtlespace_sdl_SDLRenderer
 * Method:    native_Constructor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_last_toby_turtlespace_sdl_SDLRenderer_native_1Constructor
  (JNIEnv *, jclass);

/*
 * Class:     last_toby_turtlespace_sdl_SDLRenderer
 * Method:    native_renderLine
 * Signature: (DDDDIII)V
 */
JNIEXPORT void JNICALL Java_last_toby_turtlespace_sdl_SDLRenderer_native_1renderLine
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jint, jint, jint);

/*
 * Class:     last_toby_turtlespace_sdl_SDLRenderer
 * Method:    native_cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_last_toby_turtlespace_sdl_SDLRenderer_native_1cleanup
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
